---
abstract: 'OO interface to the Plesk XML API (http://www.parallels.com/en/products/plesk/).'
author:
  - 'Ivan Sokolov <ivsokolov@cpan.org>'
build_requires:
  Test::LongString: 0
  Test::More: 0
  URI: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: API-Plesk
provides:
  API::Plesk:
    file: lib/API/Plesk.pm
    version: 2.00_2
  API::Plesk::Component:
    file: lib/API/Plesk/Component.pm
  API::Plesk::Customer:
    file: lib/API/Plesk/Customer.pm
  API::Plesk::DNS:
    file: lib/API/Plesk/DNS.pm
  API::Plesk::Database:
    file: lib/API/Plesk/Database.pm
  API::Plesk::Response:
    file: lib/API/Plesk/Response.pm
  API::Plesk::ServicePlan:
    file: lib/API/Plesk/ServicePlan.pm
  API::Plesk::ServicePlanAddon:
    file: lib/API/Plesk/ServicePlanAddon.pm
  API::Plesk::Site:
    file: lib/API/Plesk/Site.pm
  API::Plesk::Webspace:
    file: lib/API/Plesk/Webspace.pm
requires:
  Carp: 0
  Data::Dumper: 0
  HTTP::Request: 0
  LWP::UserAgent: 0
  XML::Fast: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: 2.00_2
